
import React, { createContext, useState, useEffect, useContext } from 'react';
import { User, AuthCredentials } from '@/types/form';
import { toast } from "@/components/ui/use-toast";

interface AuthContextType {
  currentUser: User | null;
  isLoading: boolean;
  login: (credentials: AuthCredentials) => Promise<User | null>;
  logout: () => Promise<void>;
  register: (credentials: AuthCredentials & { name: string }) => Promise<User | null>;
  isAuthenticated: boolean;
  isAdmin: boolean;
}

const AuthContext = createContext<AuthContextType | undefined>(undefined);

// Mock authentication service - would be replaced with real authentication
export const AuthProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [currentUser, setCurrentUser] = useState<User | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  
  // Check if user is already logged in
  useEffect(() => {
    const storedUser = localStorage.getItem('user');
    if (storedUser) {
      try {
        const parsedUser = JSON.parse(storedUser);
        setCurrentUser(parsedUser);
        setIsAuthenticated(true);
      } catch (error) {
        console.error('Error parsing stored user:', error);
        localStorage.removeItem('user');
      }
    }
    setIsLoading(false);
  }, []);

  const login = async (credentials: AuthCredentials): Promise<User | null> => {
    setIsLoading(true);
    try {
      // Mock login - would be replaced with API call
      // Simulate API delay
      await new Promise(resolve => setTimeout(resolve, 800));
      
      // For demo purposes - hardcoded admin user
      if (credentials.email === 'admin@beed.studio' && credentials.password === 'password123') {
        const user: User = {
          id: '1',
          email: 'admin@beed.studio',
          name: 'Admin User',
          role: 'admin'
        };
        
        localStorage.setItem('user', JSON.stringify(user));
        setCurrentUser(user);
        setIsAuthenticated(true);
        toast({
          title: 'Login successful',
          description: `Welcome back ${user.name || user.email}!`,
          variant: 'default',
        });
        return user;
      }
      
      // Mock demo user
      if (credentials.email === 'user@example.com' && credentials.password === 'password123') {
        const user: User = {
          id: '2',
          email: 'user@example.com',
          name: 'Demo User',
          role: 'user'
        };
        
        localStorage.setItem('user', JSON.stringify(user));
        setCurrentUser(user);
        setIsAuthenticated(true);
        toast({
          title: 'Login successful',
          description: `Welcome back ${user.name || user.email}!`,
          variant: 'default',
        });
        return user;
      }
      
      toast({
        title: 'Login failed',
        description: 'Invalid email or password',
        variant: 'destructive',
      });
      return null;
    } catch (error) {
      console.error('Login error:', error);
      toast({
        title: 'Login failed',
        description: 'An error occurred during login',
        variant: 'destructive',
      });
      return null;
    } finally {
      setIsLoading(false);
    }
  };

  const logout = async (): Promise<void> => {
    localStorage.removeItem('user');
    setCurrentUser(null);
    setIsAuthenticated(false);
    toast({
      title: 'Logout successful',
      description: 'You have been logged out',
      variant: 'default',
    });
  };

  const register = async (credentials: AuthCredentials & { name: string }): Promise<User | null> => {
    setIsLoading(true);
    try {
      // Mock registration - would be replaced with API call
      await new Promise(resolve => setTimeout(resolve, 800));
      
      const user: User = {
        id: '3', // In a real app, this would be generated by the server
        email: credentials.email,
        name: credentials.name,
        role: 'user'
      };
      
      localStorage.setItem('user', JSON.stringify(user));
      setCurrentUser(user);
      setIsAuthenticated(true);
      toast({
        title: 'Registration successful',
        description: 'Your account has been created',
        variant: 'default',
      });
      return user;
    } catch (error) {
      console.error('Registration error:', error);
      toast({
        title: 'Registration failed',
        description: 'An error occurred during registration',
        variant: 'destructive',
      });
      return null;
    } finally {
      setIsLoading(false);
    }
  };

  const isAdmin = currentUser?.role === 'admin';

  const value = {
    currentUser,
    isLoading,
    login,
    logout,
    register,
    isAuthenticated,
    isAdmin
  };

  return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>;
};

export const useAuth = () => {
  const context = useContext(AuthContext);
  if (context === undefined) {
    throw new Error('useAuth must be used within an AuthProvider');
  }
  return context;
};
