
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tsajriavcmbwgnlsonmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzYWpyaWF2Y21id2dubHNvbm1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMzMxODIsImV4cCI6MjA2MTgwOTE4Mn0.-gUjFTy1CR2gvrubQLi66Fcy_QKxQuwPIOi9F5j8g6w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper function to fetch invited users
export const fetchInvitedUsers = async () => {
  const { data, error } = await supabase
    .from('usuario_invitado')
    .select('*');
  
  if (error) {
    console.error('Error fetching invited users:', error);
    return [];
  }
  
  return data || [];
};

// Function to add a new invited user
export const addInvitedUser = async (nombre: string, correo: string) => {
  const { data, error } = await supabase
    .from('usuario_invitado')
    .insert([{ nombre, correo: correo.toLowerCase() }])
    .select();
  
  if (error) {
    console.error('Error adding invited user:', error);
    throw error;
  }
  
  return data && data[0];
};

// Function to remove an invited user
export const removeInvitedUser = async (id: number) => {
  const { error } = await supabase
    .from('usuario_invitado')
    .delete()
    .eq('id', id);
  
  if (error) {
    console.error('Error removing invited user:', error);
    throw error;
  }
  
  return true;
};

// Function to validate if a user is invited
export const validateInvitedUser = async (correo: string) => {
  console.log("Validating invited user:", correo);
  try {
    const { data, error } = await supabase
      .from('usuario_invitado')
      .select('*')
      .eq('correo', correo.toLowerCase())
      .maybeSingle();
    
    if (error && error.code !== 'PGRST116') { // Not found error code
      console.error('Error validating invited user:', error);
      return false;
    }
    
    console.log("Invited user validation result:", !!data);
    return !!data;
  } catch (err) {
    console.error("Exception validating invited user:", err);
    return false;
  }
};

// Función para registrar un nuevo administrador
export const registerAdmin = async (nombre: string, correo: string, contrasena: string) => {
  try {
    console.log("Registering admin:", { nombre, correo });
    // Insert into usuario_administrador table
    const { data, error } = await supabase
      .from('usuario_administrador')
      .insert([{ nombre, correo: correo.toLowerCase(), contrasena }])
      .select();
    
    if (error) {
      console.error('Error registrando administrador:', error);
      throw error;
    }
    
    console.log("Admin registered successfully:", data?.[0]);
    return data && data[0];
  } catch (error) {
    console.error('Error en el registro:', error);
    throw error;
  }
};

// Función para validar credenciales de administrador
export const validateAdminCredentials = async (correo: string, contrasena: string) => {
  try {
    console.log("Validating admin credentials for:", correo);
    const { data, error } = await supabase
      .from('usuario_administrador')
      .select('*')
      .eq('correo', correo.toLowerCase())
      .eq('contrasena', contrasena)
      .maybeSingle();
    
    if (error) {
      console.error('Error validando credenciales:', error);
      return null;
    }
    
    console.log("Admin validation result:", !!data);
    return data;
  } catch (error) {
    console.error('Error en la validación:', error);
    return null;
  }
};
